"""
Intelligence Actions Engine — Palantir AIP-style structured action generation.
Includes OpenSanctions API integration (free, no key required for basic use).
API: https://api.opensanctions.org/match/default

In Palantir AIP, "Actions" are AI-suggested structured tasks that human operators
can ACKNOWLEDGE, COMPLETE, or DISMISS. They bridge AI analysis → human decision.

AEGIS action types (maps to Palantir's action types):
  INVESTIGATE   — Gather more information on this entity
  MONITOR       — Increase collection posture on this entity/area
  ESCALATE      — Escalate to higher command authority
  COORDINATE    — Coordinate with partner unit or agency
  ASSESS        — Request formal intelligence assessment
  INTERCEPT     — Recommend interception / interdiction (requires approval)
  SANCTION_SCREEN — Screen entity against OpenSanctions / OFAC
  GEOFENCE_ALERT  — Alert on geofence violation

Each action has:
  - id, type, priority, status
  - target: entity uid + callsign
  - title, rationale (why the AI recommends this)
  - confidence (0–1)
  - timeSensitive (bool)
  - suggestedBy: which engine/signal triggered it
  - createdAt, expiresAt

Actions are generated by rule-based logic + optionally by LLM.
They live in memory until acknowledged/dismissed by the operator.
"""
from __future__ import annotations

import asyncio
import logging
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone, timedelta
from typing import Any

log = logging.getLogger("mss.actions")

# ── OpenSanctions integration ─────────────────────────────────────────────────
# Free API — no key required for non-commercial use
# Docs: https://api.opensanctions.org/
OPENSANCTIONS_URL = "https://api.opensanctions.org/match/default"
_sanctions_cache: dict[str, dict] = {}   # callsign → result cache (TTL: session)

# ── Action definitions ────────────────────────────────────────────────────────

ACTION_TYPES = {
    "INVESTIGATE":     {"label": "Investigate",       "color": "cyan",   "priority_weight": 1.0},
    "MONITOR":         {"label": "Monitor",           "color": "amber",  "priority_weight": 0.8},
    "ESCALATE":        {"label": "Escalate",          "color": "rose",   "priority_weight": 1.5},
    "COORDINATE":      {"label": "Coordinate",        "color": "blue",   "priority_weight": 0.9},
    "ASSESS":          {"label": "Request Assessment","color": "violet", "priority_weight": 0.7},
    "INTERCEPT":       {"label": "Recommend Intercept","color": "red",   "priority_weight": 2.0},
    "SANCTION_SCREEN": {"label": "Sanctions Screen",  "color": "orange", "priority_weight": 1.2},
    "GEOFENCE_ALERT":  {"label": "Geofence Alert",    "color": "yellow", "priority_weight": 1.3},
}

PRIORITY_LEVELS = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]


@dataclass
class IntelAction:
    id:             str
    action_type:    str         # one of ACTION_TYPES
    priority:       str         # LOW / MEDIUM / HIGH / CRITICAL
    status:         str         # PENDING / ACKNOWLEDGED / COMPLETED / DISMISSED
    target_uid:     str
    target_callsign: str
    title:          str
    rationale:      str
    confidence:     float       # 0–1
    time_sensitive: bool        = False
    suggested_by:   str         = "rule_engine"
    created_at:     str         = field(default_factory=lambda: datetime.now(timezone.utc).isoformat() + "Z")
    expires_at:     str | None  = None
    metadata:       dict        = field(default_factory=dict)

    def as_dict(self) -> dict:
        d = asdict(self)
        d["actionType"]    = d.pop("action_type")
        d["targetUid"]     = d.pop("target_uid")
        d["targetCallsign"]= d.pop("target_callsign")
        d["timeSensitive"] = d.pop("time_sensitive")
        d["suggestedBy"]   = d.pop("suggested_by")
        d["createdAt"]     = d.pop("created_at")
        d["expiresAt"]     = d.pop("expires_at")
        d["label"]         = ACTION_TYPES.get(self.action_type, {}).get("label", self.action_type)
        d["color"]         = ACTION_TYPES.get(self.action_type, {}).get("color", "gray")
        return d


# ── In-memory action store ────────────────────────────────────────────────────
# In production this would be a database. In dev mode: in-memory dict.
_actions: dict[str, IntelAction] = {}

def _make_id() -> str:
    return f"ACT-{uuid.uuid4().hex[:8].upper()}"

def _expires(hours: int = 4) -> str:
    return (datetime.now(timezone.utc) + timedelta(hours=hours)).isoformat() + "Z"


# ── OpenSanctions screening ───────────────────────────────────────────────────

async def check_opensanctions(callsign: str, entity_type: str = "vessel") -> dict:
    """
    Screen a callsign/name against OpenSanctions database.
    Free API — no key required. Returns match result with confidence.

    Uses the /match/default endpoint which covers:
    - OFAC SDN list, UN Security Council, EU sanctions
    - 600+ sources globally, updated daily
    """
    if callsign in _sanctions_cache:
        return _sanctions_cache[callsign]

    try:
        import httpx
        # Map entity type to OpenSanctions schema
        schema = "Vessel" if entity_type == "vessel" else "Aircraft" if entity_type == "aircraft" else "LegalEntity"
        payload = {
            "queries": {
                "q1": {
                    "schema":     schema,
                    "properties": {"name": [callsign]},
                }
            }
        }
        async with httpx.AsyncClient(timeout=8.0) as client:
            resp = await client.post(
                OPENSANCTIONS_URL,
                json=payload,
                headers={"Accept": "application/json"},
            )
            if resp.status_code == 200:
                data = resp.json()
                results  = data.get("responses", {}).get("q1", {}).get("results", [])
                top_match = results[0] if results else None
                result = {
                    "screened":    True,
                    "matched":     bool(top_match),
                    "score":       top_match.get("score", 0) if top_match else 0,
                    "matchedName": top_match.get("caption") if top_match else None,
                    "datasets":    top_match.get("datasets", []) if top_match else [],
                    "callsign":    callsign,
                }
            else:
                result = {"screened": False, "error": f"HTTP {resp.status_code}", "callsign": callsign}
    except Exception as e:
        result = {"screened": False, "error": str(e), "callsign": callsign}

    _sanctions_cache[callsign] = result
    return result


async def screen_entities_batch(entities: list[dict]) -> dict[str, dict]:
    """Screen multiple entities against OpenSanctions in parallel."""
    tasks = {
        e["uid"]: asyncio.create_task(
            check_opensanctions(e.get("callsign", e["uid"][:8]), e.get("entityType", "ground"))
        )
        for e in entities if e.get("uid")
    }
    results = {}
    for uid, task in tasks.items():
        try:
            results[uid] = await task
        except Exception:
            results[uid] = {"screened": False}
    return results


# ── Rule-based action generation ──────────────────────────────────────────────

def generate_actions(
    entities:  list[dict],
    threats:   list[dict],
    anomalies: list[dict],
    pol_deviations: list[dict] | None = None,
    links:     list[dict] | None = None,
) -> list[IntelAction]:
    """
    Generate intelligence actions from current operational picture.
    Clears stale pending actions before generating new ones.
    Returns list of newly generated actions.
    """
    new_actions: list[IntelAction] = []
    uid_to_entity = {e["uid"]: e for e in entities if e.get("uid")}

    # ── Rule 1: Critical/High threat entities → ESCALATE ────────────────────���
    for t in threats:
        uid   = t.get("uid", "")
        score = t.get("score", 0)
        level = t.get("level", "Low")
        if level not in ("Critical", "High"):
            continue
        e = uid_to_entity.get(uid, {})
        cs = e.get("callsign") or uid[:8]

        action_type = "ESCALATE" if level == "Critical" else "MONITOR"
        priority    = "CRITICAL" if level == "Critical" else "HIGH"

        act = IntelAction(
            id              = _make_id(),
            action_type     = action_type,
            priority        = priority,
            status          = "PENDING",
            target_uid      = uid,
            target_callsign = cs,
            title           = f"{action_type}: {cs} — Threat Score {score}/100",
            rationale       = (
                f"Entity {cs} ({e.get('entityType', '?')}/{e.get('affiliation', '?')}) "
                f"has reached threat level {level} (score {score}/100). "
                f"Reasons: {'; '.join(t.get('reasons', ['elevated indicators'])[:3])}."
            ),
            confidence      = t.get("confidence", 0.7),
            time_sensitive  = level == "Critical",
            suggested_by    = "threat_engine",
            expires_at      = _expires(2 if level == "Critical" else 6),
            metadata        = {"threatLevel": level, "threatScore": score},
        )
        new_actions.append(act)

    # ── Rule 2: Dark ships → SANCTION_SCREEN ─────────────────────────────────
    for a in anomalies:
        if "DARK_SHIP" not in (a.get("flags") or []):
            continue
        uid = a.get("entityUid", "")
        e   = uid_to_entity.get(uid, {})
        cs  = e.get("callsign") or uid[:8]
        act = IntelAction(
            id              = _make_id(),
            action_type     = "SANCTION_SCREEN",
            priority        = "HIGH",
            status          = "PENDING",
            target_uid      = uid,
            target_callsign = cs,
            title           = f"SANCTION_SCREEN: {cs} — AIS dark vessel",
            rationale       = (
                f"Vessel {cs} conducting AIS-off behavior. "
                "Screen against OFAC/OpenSanctions for sanctions violations. "
                "Pattern consistent with illicit oil transfer or sanctions evasion."
            ),
            confidence      = 0.75,
            time_sensitive  = False,
            suggested_by    = "anomaly_engine",
            expires_at      = _expires(12),
            metadata        = {"flags": a.get("flags"), "anomalyScore": a.get("score")},
        )
        new_actions.append(act)

    # ── Rule 3: Impossible speed / spoofing → INVESTIGATE ────────────────────
    for a in anomalies:
        if "IMPOSSIBLE_SPEED" not in (a.get("flags") or []) and \
           "HEADING_THRASH" not in (a.get("flags") or []):
            continue
        uid = a.get("entityUid", "")
        e   = uid_to_entity.get(uid, {})
        cs  = e.get("callsign") or uid[:8]
        act = IntelAction(
            id              = _make_id(),
            action_type     = "INVESTIGATE",
            priority        = "MEDIUM",
            status          = "PENDING",
            target_uid      = uid,
            target_callsign = cs,
            title           = f"INVESTIGATE: {cs} — Possible spoofing / anomalous behavior",
            rationale       = (
                f"Anomaly flags detected on {cs}: {', '.join(a.get('flags', []))}. "
                "Possible AIS/ADS-B spoofing, technical malfunction, or deceptive maneuvering."
            ),
            confidence      = 0.65,
            time_sensitive  = False,
            suggested_by    = "anomaly_engine",
            expires_at      = _expires(8),
            metadata        = {"flags": a.get("flags")},
        )
        new_actions.append(act)

    # ── Rule 4: PoL out-of-area → MONITOR ─────────────────────────���──────────
    for pol in (pol_deviations or []):
        if "OUT_OF_AREA" not in (pol.get("flags") or []):
            continue
        uid = pol.get("entityUid", "")
        e   = uid_to_entity.get(uid, {})
        cs  = e.get("callsign") or uid[:8]
        act = IntelAction(
            id              = _make_id(),
            action_type     = "MONITOR",
            priority        = "MEDIUM",
            status          = "PENDING",
            target_uid      = uid,
            target_callsign = cs,
            title           = f"MONITOR: {cs} — Operating outside pattern of life",
            rationale       = (
                f"Entity {cs} is operating outside its established behavioral area. "
                f"Deviation score: {pol.get('deviationScore', 0):.2f}. "
                f"Flags: {', '.join(pol.get('flags', []))}."
            ),
            confidence      = 0.7,
            time_sensitive  = False,
            suggested_by    = "pol_engine",
            expires_at      = _expires(6),
            metadata        = {"polFlags": pol.get("flags"), "deviationScore": pol.get("deviationScore")},
        )
        new_actions.append(act)

    # ── Rule 5: Large hostile formation → COORDINATE ─────────────────────────
    hostile_count = sum(1 for e in entities if e.get("affiliation") == "hostile")
    if hostile_count >= 5:
        act = IntelAction(
            id              = _make_id(),
            action_type     = "COORDINATE",
            priority        = "HIGH",
            status          = "PENDING",
            target_uid      = "AREA-HOSTILE",
            target_callsign = f"{hostile_count} HOSTILE TRACKS",
            title           = f"COORDINATE: {hostile_count} hostile entities in operational area",
            rationale       = (
                f"Concentration of {hostile_count} hostile-affiliated entities detected. "
                "Recommend coordination with partner elements and ISR tasking to establish "
                "order of battle and likely course of action."
            ),
            confidence      = 0.8,
            time_sensitive  = hostile_count >= 10,
            suggested_by    = "situational_awareness",
            expires_at      = _expires(3),
            metadata        = {"hostileCount": hostile_count},
        )
        new_actions.append(act)

    # ── Rule 6: PyOD ML anomaly → INVESTIGATE ────────────────────────────────
    for pol in (pol_deviations or []):
        if "ML_ANOMALY" not in (pol.get("flags") or []):
            continue
        uid = pol.get("entityUid", "")
        e   = uid_to_entity.get(uid, {})
        cs  = e.get("callsign") or uid[:8]
        ml_score = pol.get("mlScore", 0)
        act = IntelAction(
            id              = _make_id(),
            action_type     = "INVESTIGATE",
            priority        = "HIGH",
            status          = "PENDING",
            target_uid      = uid,
            target_callsign = cs,
            title           = f"INVESTIGATE: {cs} — ML behavioral anomaly",
            rationale       = (
                f"IsolationForest + LOF ensemble detected {cs} as a behavioral outlier "
                f"(ML anomaly score: {ml_score:.0%}). The entity's recent track pattern "
                "deviates significantly from its historical norm in ways not captured by "
                "simple threshold rules."
            ),
            confidence      = min(0.95, 0.6 + ml_score * 0.35),
            time_sensitive  = ml_score > 0.8,
            suggested_by    = "pol_engine:pyod",
            expires_at      = _expires(4),
            metadata        = {"mlScore": ml_score, "polFlags": pol.get("flags")},
        )
        new_actions.append(act)

    # ── Store new actions (merge with existing, avoid duplicates) ─────────────
    # Use target_uid + action_type as dedup key — one action per type per entity
    existing_keys = {
        (a.target_uid, a.action_type)
        for a in _actions.values()
        if a.status == "PENDING"
    }
    added = []
    for act in new_actions:
        key = (act.target_uid, act.action_type)
        if key not in existing_keys:
            _actions[act.id] = act
            existing_keys.add(key)
            added.append(act)

    return added


def get_pending_actions(limit: int = 50) -> list[IntelAction]:
    """Return all pending actions sorted by priority."""
    priority_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
    pending = [a for a in _actions.values() if a.status == "PENDING"]
    return sorted(pending, key=lambda a: (priority_order.get(a.priority, 9), a.created_at))[:limit]


def update_action_status(action_id: str, status: str) -> bool:
    """Update status of an action (ACKNOWLEDGED / COMPLETED / DISMISSED)."""
    if action_id in _actions and status in ("ACKNOWLEDGED", "COMPLETED", "DISMISSED"):
        _actions[action_id].status = status
        return True
    return False


def get_action_summary() -> dict:
    """Summary counts for the HUD."""
    all_a = list(_actions.values())
    return {
        "total":        len(all_a),
        "pending":      sum(1 for a in all_a if a.status == "PENDING"),
        "critical":     sum(1 for a in all_a if a.status == "PENDING" and a.priority == "CRITICAL"),
        "high":         sum(1 for a in all_a if a.status == "PENDING" and a.priority == "HIGH"),
        "acknowledged": sum(1 for a in all_a if a.status == "ACKNOWLEDGED"),
        "completed":    sum(1 for a in all_a if a.status == "COMPLETED"),
    }
