-- ============================================================================
-- Roles hardening — beta tester tier + self-escalation fix
-- ============================================================================
-- Before this migration, `profiles` had an RLS UPDATE policy that only checked
-- row ownership (auth.uid() = id), which meant any authenticated user could
-- flip their own `is_admin = true` or `role = 'admin'` and grant themselves
-- admin. This migration:
--
--   1. Adds an `is_beta_tester` boolean flag (defaults false)
--   2. Scrubs admin/role from every account except the grandfathered admin
--   3. Installs a BEFORE UPDATE trigger that blocks non-admins from changing
--      the privilege columns (role / is_admin / is_beta_tester) on any row,
--      including their own — service-role (migrations, edge functions) bypasses
--   4. Adds admin-only RPCs: grant_beta_tester / revoke_beta_tester / grant_admin
--   5. Adds a simple audit log for role changes
--   6. Adds public helpers `current_user_is_admin()` and
--      `current_user_is_beta_tester()` so the client can render the right UI
--      without a round-trip to `profiles`
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Column
-- ----------------------------------------------------------------------------
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS is_beta_tester boolean NOT NULL DEFAULT false;

-- ----------------------------------------------------------------------------
-- 2. Defensive sweep — strip admin from anyone who shouldn't have it.
--    Grandfather exactly one UUID (the operator who ran the previous
--    deployment). Change this UUID if you want a different admin seed.
-- ----------------------------------------------------------------------------
UPDATE profiles
SET role = NULL, is_admin = false
WHERE is_admin = true
  AND id <> '1e5ac55b-8898-44ac-9aa8-cd5a657618d3'::uuid;

-- ----------------------------------------------------------------------------
-- 3. Helper functions (STABLE, SECURITY DEFINER so they bypass RLS when
--    reading profile rows on behalf of the caller)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.current_user_is_admin()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT (is_admin OR role = 'admin') FROM profiles WHERE id = auth.uid()),
    false
  );
$$;

CREATE OR REPLACE FUNCTION public.current_user_is_beta_tester()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT (is_beta_tester OR is_admin OR role = 'admin') FROM profiles WHERE id = auth.uid()),
    false
  );
$$;

GRANT EXECUTE ON FUNCTION public.current_user_is_admin() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_is_beta_tester() TO anon, authenticated;

-- ----------------------------------------------------------------------------
-- 4. Privilege-escalation guard trigger
--    Fires on every UPDATE to `profiles`. Raises if a non-admin tries to
--    change role/is_admin/is_beta_tester. service_role bypasses.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.prevent_privilege_escalation()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_jwt_role text;
  v_caller_is_admin boolean;
BEGIN
  -- Service role (pg_cron, Edge Functions, migrations) can do anything
  v_jwt_role := current_setting('request.jwt.claim.role', true);
  IF v_jwt_role = 'service_role' THEN
    RETURN NEW;
  END IF;

  -- Detect attempts to change the privilege columns
  IF NEW.role IS DISTINCT FROM OLD.role
     OR NEW.is_admin IS DISTINCT FROM OLD.is_admin
     OR NEW.is_beta_tester IS DISTINCT FROM OLD.is_beta_tester
  THEN
    SELECT (is_admin OR role = 'admin')
    INTO v_caller_is_admin
    FROM profiles
    WHERE id = auth.uid();

    IF COALESCE(v_caller_is_admin, false) = false THEN
      RAISE EXCEPTION
        'privilege escalation blocked: only admins can change role/is_admin/is_beta_tester';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_privilege_guard ON profiles;
CREATE TRIGGER profiles_privilege_guard
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION public.prevent_privilege_escalation();

-- ----------------------------------------------------------------------------
-- 5. Audit log for privilege changes (created before the RPCs that write to it)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS privilege_audit (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id  uuid,
  target_id uuid NOT NULL,
  action    text NOT NULL,
  details   jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE privilege_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_read_privilege_audit ON privilege_audit;
CREATE POLICY admin_read_privilege_audit ON privilege_audit
  FOR SELECT USING (public.current_user_is_admin());

-- ----------------------------------------------------------------------------
-- 6. Admin-only RPCs to promote / demote users
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.grant_beta_tester(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.current_user_is_admin() THEN
    RAISE EXCEPTION 'admin role required';
  END IF;
  UPDATE profiles SET is_beta_tester = true WHERE id = p_user_id;
  INSERT INTO privilege_audit (actor_id, target_id, action, details)
  VALUES (auth.uid(), p_user_id, 'grant_beta_tester', NULL);
END;
$$;

CREATE OR REPLACE FUNCTION public.revoke_beta_tester(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.current_user_is_admin() THEN
    RAISE EXCEPTION 'admin role required';
  END IF;
  UPDATE profiles SET is_beta_tester = false WHERE id = p_user_id;
  INSERT INTO privilege_audit (actor_id, target_id, action, details)
  VALUES (auth.uid(), p_user_id, 'revoke_beta_tester', NULL);
END;
$$;

CREATE OR REPLACE FUNCTION public.grant_admin(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.current_user_is_admin() THEN
    RAISE EXCEPTION 'admin role required';
  END IF;
  UPDATE profiles SET is_admin = true, role = 'admin' WHERE id = p_user_id;
  INSERT INTO privilege_audit (actor_id, target_id, action, details)
  VALUES (auth.uid(), p_user_id, 'grant_admin', NULL);
END;
$$;

CREATE OR REPLACE FUNCTION public.revoke_admin(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.current_user_is_admin() THEN
    RAISE EXCEPTION 'admin role required';
  END IF;
  -- Safety: don't let an admin demote themselves into a fully admin-less state.
  IF p_user_id = auth.uid() THEN
    IF (SELECT count(*) FROM profiles WHERE is_admin = true AND id <> p_user_id) = 0 THEN
      RAISE EXCEPTION 'cannot demote the last remaining admin';
    END IF;
  END IF;
  UPDATE profiles SET is_admin = false, role = NULL WHERE id = p_user_id;
  INSERT INTO privilege_audit (actor_id, target_id, action, details)
  VALUES (auth.uid(), p_user_id, 'revoke_admin', NULL);
END;
$$;

GRANT EXECUTE ON FUNCTION public.grant_beta_tester(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_beta_tester(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_admin(uuid) TO authenticated;

-- ----------------------------------------------------------------------------
-- 7. Tighten profile visibility — admin flags are readable by the owner and by
--    other admins, not by the general public. Keep display_name / country_code
--    / game_state behaviour unchanged (handled by the existing SELECT policy).
-- ----------------------------------------------------------------------------
-- (The existing "Anyone can read profiles" policy lets everyone see all
-- columns, which is fine for display_name but leaks is_admin flags. We leave
-- it as-is for now because the client already relies on cross-profile reads
-- for leaderboards; revisit if / when leaderboards stop using profiles.)

COMMENT ON COLUMN profiles.is_beta_tester IS
  'If true, the user sees the DevPanel (F2) and can manipulate their own game state. Granted via grant_beta_tester() RPC. Admins implicitly include beta tester powers.';

COMMENT ON FUNCTION public.current_user_is_admin() IS
  'Returns true if the authenticated caller is flagged as admin. Used by client UI and RLS policies.';

COMMENT ON FUNCTION public.current_user_is_beta_tester() IS
  'Returns true if the authenticated caller is a beta tester OR admin. Used by client UI to gate DevPanel.';
